#!/bin/bash
export DIRMAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
source $DIRMAIN/config

echo "listening on TCP port $PORT"
socat tcp-l:$PORT,fork open:"main" &

while :
do
	nc -l -p $NCPORT > tmp
	if [[ -f "tmp" ]];
	then
		cat "tmp" >> main
		rm -f tmp
	fi
done
